import { NextRequest, NextResponse } from "next/server";
import { converse } from "@/lib/bossman/converse";

// POST /api/bossman/converse
// Body: { message: string }
// The live conversational brain behind the console. Returns Bossman's reply,
// clarifying question, plan, approval gate, and report — generated by Claude
// when ANTHROPIC_API_KEY is set, heuristic otherwise.
export async function POST(req: NextRequest) {
  let message = "";
  try {
    const body = await req.json();
    message = typeof body?.message === "string" ? body.message : "";
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!message.trim()) {
    return NextResponse.json({ error: "message is required" }, { status: 400 });
  }

  const result = await converse(message);
  return NextResponse.json(result);
}
